import { IconProp } from "@fortawesome/fontawesome-svg-core";
import {
  faCalculator,
  faFlask,
  faBook,
  faGlobe,
  faLaptopCode,
  faPalette,
  faComments,
  faPhoneAlt,
  faShareAlt,
  faEnvelope,
  faSearch,
  faSlidersH,
  faFilter,
  faSort,
  faChartPie,
  faTable,
  faDatabase,
  faFileAlt,
  faCamera,
  faQuestion,
  faCogs,
  faCodeBranch,
  faUser,
  faGraduationCap,
  faHandshake,
  faUsers,
  faChartLine,
  faMoneyBill,
  faBriefcase,
  faBullhorn,
  faTools,
  faGavel,
  faLightbulb,
  faPlaneDeparture,
} from "@fortawesome/free-solid-svg-icons";

type iconData = {
  faIcon: IconProp;
  isSelected: boolean;
};

export const iconData: iconData[] = [
  { faIcon: faFlask, isSelected: true },
  { faIcon: faBook, isSelected: false },
  { faIcon: faCalculator, isSelected: false },
  { faIcon: faGlobe, isSelected: false },
  { faIcon: faLaptopCode, isSelected: false },
  { faIcon: faPalette, isSelected: false },
  { faIcon: faComments, isSelected: false },
  { faIcon: faPhoneAlt, isSelected: false },
  { faIcon: faShareAlt, isSelected: false },
  { faIcon: faEnvelope, isSelected: false },
  { faIcon: faSearch, isSelected: false },
  { faIcon: faSlidersH, isSelected: false },
  { faIcon: faFilter, isSelected: false },
  { faIcon: faSort, isSelected: false },
  { faIcon: faChartPie, isSelected: false },
  { faIcon: faTable, isSelected: false },
  { faIcon: faDatabase, isSelected: false },
  { faIcon: faFileAlt, isSelected: false },
  { faIcon: faCamera, isSelected: false },
  { faIcon: faQuestion, isSelected: false },
  { faIcon: faCogs, isSelected: false },
  { faIcon: faCodeBranch, isSelected: false },
  { faIcon: faUser, isSelected: false },
  { faIcon: faGraduationCap, isSelected: false },
  { faIcon: faUsers, isSelected: false },
  { faIcon: faHandshake, isSelected: false },
  { faIcon: faChartLine, isSelected: false },
  { faIcon: faMoneyBill, isSelected: false },
  { faIcon: faBriefcase, isSelected: false },
  { faIcon: faBullhorn, isSelected: false },
  { faIcon: faTools, isSelected: false },
  { faIcon: faGavel, isSelected: false },
  { faIcon: faLightbulb, isSelected: false },
  { faIcon: faPlaneDeparture, isSelected: false },
];
